import type { Metadata } from "next";
import {Noto_Serif_Bengali} from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";
import Footer from "./component/Footer"

const notoSerifBengali = Noto_Serif_Bengali({
  subsets: ["latin","bengali"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoSerifBengali.className} min-h-full flex flex-col bg-[#E1E8E1] antialiased`}
    >
      <body className="min-h-screen flex flex-col">
        <div className="flex-1 flex flex-col">
       <Navbar/>
       <main>
        {children}
        </main>
        </div>
        <Footer/>
        
        </body>
    </html>
  );
}
